version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/task-1
      - AUTH_SERVER_URI=http://localhost:3000
    depends_on:
      - mongo
  mongo:
    image: mongo:6.0-rc